name: Add needs-review and size/XL pull requests to projects

on:
  issues:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add issues to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/timja/projects/3
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: ux
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/timja/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: bug
