name: Remove label command
on:
  repository_dispatch:
    types: [remove-label-command]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: ${{ github.event.client_payload.slash_command.args.unnamed.all }}
          number: ${{ github.event.client_payload.github.payload.issue.number }}
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
